version: '3.6'

services:

    node12:
        build:
            context: .
            dockerfile: Dockerfile-12
        working_dir: /app
        volumes:
          - ./coverage:/app/coverage
        command: node test.js --silent

    node14:
        build:
            context: .
            dockerfile: Dockerfile-14
        working_dir: /app
        volumes:
          - ./coverage:/app/coverage
        command: node test.js --silent
#        command: nyc --reporter=lcov --reporter=text-summary node --unhandled-rejections=strict test.js --silent

    node15:
        build:
            context: .
            dockerfile: Dockerfile-15
        working_dir: /app
        volumes:
          - ./coverage:/app/coverage
        command: node test.js --silent