version: '3.6'

services:

    node12:
        build:
            context: .
            dockerfile: Dockerfile-12
        working_dir: /app
        volumes:
          - ./coverage:/app/coverage
        command: node test.js

    node14:
        build:
            context: .
            dockerfile: Dockerfile-14
        working_dir: /app
        volumes:
          - ./coverage:/app/coverage
#        command: node test.js
        command: nyc --reporter=lcov --reporter=text-summary node --unhandled-rejections=strict test.js

    node15:
        build:
            context: .
            dockerfile: Dockerfile-15
        working_dir: /app
        volumes:
          - ./coverage:/app/coverage
        command: node test.js

    node16:
        build:
            context: .
            dockerfile: Dockerfile-16
        working_dir: /app
        volumes:
          - ./coverage:/app/coverage
        command: node test.js

#    node-test:
#        build:
#            context: .
#            dockerfile: Dockerfile-16
#        working_dir: /app
#        volumes:
##          - ./coverage:/app/coverage
#            - ./:/app
#        command: nodemon -L test.js
