# This workflow will do a clean install of NodeJS 18.x on linux for every push or pull request on master
# It will then run the tests of the app.

name: linux-18.x

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: npm i
    - run: npm run build --if-present
    - run: node test.js
