# This workflow will do a clean install of NodeJS 17.x on windows for every push or pull request on master
# It will then run the tests of the app

name: windows-17.x

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v1
      with:
        node-version: 17.x
    - run: npm i
    - run: npm run build --if-present
    - run: node test.js
